[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.1"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.0.0"

[[constraint]]
  name = "github.com/DATA-DOG/go-sqlmock"
  version = "1.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
